# -- Alternatively, if the beginning of this file has the line
# '#!/usr/bin/env ansible-playbook', we can execute this playbook
# as './web-nots.yml'
#
# ansible-doc is a great command to learn about ansible modules
---
- name: Configure webserver with nginx
  hosts: webservers
  become: true
  become_method: sudo # 'sudo' is the default become_method
  tasks:
    - name: install nginx
      apt: name=nginx update_cache=yes
    - name: copy nginx config file
      copy: src=files/nginx.conf dest=/etc/nginx/sites-available/default
    - name: enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link
    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html
        mode=0644
    - name: restart nginx
      service: name=nginx state=restarted
