---
- name: Configure webserver with nginx and tls
  hosts: webservers
  become: True
  become_method: sudo
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/sites-available/default
    server_name: localhost
  tasks:
    - name: Install nginx
      apt: name=nginx update_cache=yes cache_valid_time=3600
    - name: create directories for ssl certificates
      file: path=/etc/nginx/ssl state=directory
    - name: copy TLS key
      copy: src=files/nginx.key dest={{ key_file }} owner=root mode=0600
      notify: restart nginx # only triggered if the task changed the host's state
    - name: copy TLS certificate
      copy: src=files/nginx.crt dest={{ cert_file }}
      notify: restart nginx
    - name: copy nginx config file
      template: src=templates/nginx.conf.j2 dest={{ conf_file }}
      notify: restart nginx
    - name: enable configuration
      file: dest=/etc/nginx/sites-enabled/default src={{ conf_file }} state=link
      notify: restart nginx
    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html
        mode=0644
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

# Handlers only run after all the tests are run, and they only run once, even if they
# are notified multiple times. They always run in the order that appeared on the play,
# not the notification order.
#
# CAVEAT:
# 1. I run a playbook
# 2. One of my tasks with a 'notify' on it changes state
# 3. An error occurs on a subsequent task, stopping Ansible
# 4. I fix the error in my playbook
# 5. I run Ansible again
# 6. None of the tasks report a state change the second time around, so Ansible doesn't run the handler
